/// Фічі, що не займають дії, а спрацьовують на кидку атаки, після влучання чи промаху.
/// Лист показує їх окремим розділом «Під час атаки», а не серед пасивних.
const FEATURES_USED_DURING_ATTACK = new Set<string>([
  "Ancestral Protectors",
  "Arcane Jolt",
  "Brutal Critical",
  "Channel Divinity: Guided Strike (Oath of Conquest)",
  "Channel Divinity: Guided Strike (War Domain)",
  "Colossus Slayer (Hunter)",
  "Death Strike",
  "Disarming Attack",
  "Distracting Strike",
  "Divine Fury",
  "Divine Smite",
  "Divine Strike (Death)",
  "Divine Strike (Forge)",
  "Divine Strike (Life)",
  "Divine Strike (Nature)",
  "Divine Strike (Order)",
  "Divine Strike (Tempest)",
  "Divine Strike (Trickery)",
  "Divine Strike (Twilight)",
  "Divine Strike (War)",
  "Dreadful Strikes",
  "Eldritch Smite",
  "Eldritch Strike",
  "Favored Foe",
  "Focused Aim",
  "Foe Slayer",
  "Gathered Swarm",
  "Goading Attack",
  "Horde Breaker (Hunter)",
  "Hurl Through Hell",
  "Improved Divine Smite",
  "Lifedrinker",
  "Lunging Attack",
  "Maneuvering Attack",
  "Menacing Attack",
  "Precision Attack",
  "Psionic Strike",
  "Psychic Blades (College of Whispers)",
  "Pushing Attack",
  "Rapid Strike",
  "Reckless Attack",
  "Relentless Avenger",
  "Savage Attacks",
  "Sneak Attack",
  "Stalker's Flurry",
  "Stunning Strike",
  "Surprise Attack",
  "Sweeping Attack",
  "Trip Attack",

  "Assassin: Death Strike (2024)",
  "Barbarian: Brutal Strike (2024)",
  "Barbarian: Improved Brutal Strike L13 (2024)",
  "Barbarian: Improved Brutal Strike L17 (2024)",
  "Barbarian: Reckless Attack (2024)",
  "Class Choice Feature: Blessed Strikes: Divine Strike (2024)",
  "Class Choice Feature: Elemental Fury: Primal Strike (2024)",
  "Eldritch Knight: Eldritch Strike (2024)",
  "Eldritch Smite (2024)",
  "Fey Wanderer: Dreadful Strikes (2024)",
  "Fighter: Studied Attacks (2024)",
  "Gloom Stalker: Stalker's Flurry (2024)",
  "Lifedrinker (2024)",
  "Monk: Stunning Strike (2024)",
  "Origin Feat: Savage Attacker (2024)",
  "Paladin: Radiant Strikes (2024)",
  "Path of the Berserker: Frenzy (2024)",
  "Path of the Zealot: Divine Fury (2024)",
  "Rogue: Cunning Strike (2024)",
  "Rogue: Devious Strikes (2024)",
  "Rogue: Improved Cunning Strike (2024)",
  "Rogue: Sneak Attack (2024)",
  "Subclass Choice Feature: Commander’s Strike (2024)",
  "Subclass Choice Feature: Disarming Attack (2024)",
  "Subclass Choice Feature: Distracting Strike (2024)",
  "Subclass Choice Feature: Goading Attack (2024)",
  "Subclass Choice Feature: Hunter's Prey: Colossus Slayer (2024)",
  "Subclass Choice Feature: Hunter's Prey: Horde Breaker (2024)",
  "Subclass Choice Feature: Maneuvering Attack (2024)",
  "Subclass Choice Feature: Menacing Attack (2024)",
  "Subclass Choice Feature: Precision Attack (2024)",
  "Subclass Choice Feature: Pushing Attack (2024)",
  "Subclass Choice Feature: Sweeping Attack (2024)",
  "Subclass Choice Feature: Trip Attack (2024)",
]);

export function isUsedDuringAttack(engName: string | null | undefined): boolean {
  return engName != null && FEATURES_USED_DURING_ATTACK.has(engName);
}

export function listFeaturesUsedDuringAttack(): string[] {
  return [...FEATURES_USED_DURING_ATTACK];
}
