-- KR31.2: missing 2024 subclasses from the owner-approved Wikidot inventory.
-- Apply before seeding subclasses and deploying the refreshed catalog.

ALTER TYPE "Subclasses" ADD VALUE IF NOT EXISTS 'BLADESINGER';
ALTER TYPE "Subclasses" ADD VALUE IF NOT EXISTS 'CARTOGRAPHER';
ALTER TYPE "Subclasses" ADD VALUE IF NOT EXISTS 'COLLEGE_OF_THE_MOON';
ALTER TYPE "Subclasses" ADD VALUE IF NOT EXISTS 'CONJURER';
ALTER TYPE "Subclasses" ADD VALUE IF NOT EXISTS 'ENCHANTER';
ALTER TYPE "Subclasses" ADD VALUE IF NOT EXISTS 'HOLLOW_WARDEN';
ALTER TYPE "Subclasses" ADD VALUE IF NOT EXISTS 'NECROMANCER';
ALTER TYPE "Subclasses" ADD VALUE IF NOT EXISTS 'OATH_OF_THE_NOBLE_GENIES';
ALTER TYPE "Subclasses" ADD VALUE IF NOT EXISTS 'REANIMATOR';
ALTER TYPE "Subclasses" ADD VALUE IF NOT EXISTS 'SCION_OF_THE_THREE';
ALTER TYPE "Subclasses" ADD VALUE IF NOT EXISTS 'SHADOW_SORCERY';
ALTER TYPE "Subclasses" ADD VALUE IF NOT EXISTS 'SPELLFIRE_SORCERY';
ALTER TYPE "Subclasses" ADD VALUE IF NOT EXISTS 'TRANSMUTER';
ALTER TYPE "Subclasses" ADD VALUE IF NOT EXISTS 'UNDEAD_PATRON';
ALTER TYPE "Subclasses" ADD VALUE IF NOT EXISTS 'VESTIGE_PATRON';
ALTER TYPE "Subclasses" ADD VALUE IF NOT EXISTS 'WARRIOR_OF_THE_MYSTIC_ARTS';
ALTER TYPE "Subclasses" ADD VALUE IF NOT EXISTS 'WINTER_WALKER';
