/// Партії перекладу KR16.2 і O17: записи, чий український текст уже описує правило 2024,
/// а не 2014. Список працює як храповик — кожна партія доливає імена, і жодне з них більше
/// не має права розійтися з XPHB.
///
/// Живе окремим модулем, бо його читають дві перевірки: звірка **полів**
/// (`differs-from-2014.test.ts`) і звірка **прози** (`spells-prose-2024.test.ts`).
/// Два списки розійшлися б із першою ж партією.
export const ALIGNED_WITH_XPHB: Record<string, string[]> = {
  "партія 1": [
    "Chill Touch",
    "Friends",
    "Message",
    "Mind Sliver",
    "Produce Flame",
    "Resistance",
    "Shillelagh",
    "Spare the Dying",
    "Thunderclap",
    "Vicious Mockery",
    "Word of Radiance",
    "Armor of Agathys",
    "Arms of Hadar",
    "Color Spray",
    "Command",
    "Detect Evil and Good",
    "Detect Magic",
    "Detect Poison and Disease",
    "False Life",
    "Goodberry",
    "Inflict Wounds",
    "Jump",
    "Witch Bolt",
    "Cordon of Arrows",
    "Enhance Ability",
    "Find Steed",
    "Gust of Wind",
    "Lesser Restoration",
    "Mind Spike",
    "Mirror Image",
  ],
  "партія 2": [
    "Pass without Trace",
    "Phantasmal Force",
    "Ray of Enfeeblement",
    "Aura of Vitality",
    "Blink",
    "Conjure Animals",
    "Conjure Barrage",
    "Crusader's Mantle",
    "Hunger of Hadar",
    "Leomund's Tiny Hut",
    "Speak with Plants",
    "Spirit Guardians",
    "Wind Wall",
    "Aura of Life",
    "Aura of Purity",
    "Banishment",
    "Confusion",
    "Conjure Minor Elementals",
    "Conjure Woodland Beings",
    "Grasping Vine",
    "Ice Storm",
    "Leomund's Secret Chest",
    "Antilife Shell",
    "Bigby's Hand",
    "Circle of Power",
    "Commune with Nature",
    "Conjure Elemental",
    "Contagion",
    "Destructive Wave",
    "Dream",
  ],
  "партія 3": [
    "Flame Strike",
    "Swift Quiver",
    "Yolande's Regal Presence",
    "Circle of Death",
    "Conjure Fey",
    "Globe of Invulnerability",
    "Guards and Wards",
    "Heroes' Feast",
    "Transport Via Plants",
    "Conjure Celestial",
    "Mordenkainen's Sword",
    "Prismatic Spray",
    "Teleport",
    "Antimagic Field",
    "Control Weather",
    "Holy Aura",
    "Tsunami",
    "Astral Projection",
    "Power Word Heal",
    "Power Word Kill",
    "Prismatic Wall",
    "Storm of Vengeance",
    "Weird",
  ],
  "партія 4": [
    "Divine Favor",
    "Sending",
    "Forcecage",
    "Poison Spray",
    "Healing Word",
    "Spiritual Weapon",
    "Cure Wounds",
    "Magic Weapon",
    "Mass Healing Word",
    "Blindness/Deafness",
    "Mass Cure Wounds",
    "Enthrall",
    "Hail of Thorns",
    "Animal Shapes",
    "Thunderous Smite",
    "Earthquake",
    "Lightning Arrow",
    "Searing Smite",
    "Barkskin",
    "Reincarnate",
    "Blinding Smite",
    "Giant Insect",
    "Sleep",
    "Blade Ward",
    "True Strike",
    "Wrathful Smite",
    "Staggering Smite",
    "Hex",
    "Flame Blade",
    "Toll the Dead",
    "Dragon's Breath",
    "Melf's Acid Arrow",
  ],
  "поза партіями": ["Bestow Curse", "Animate Objects"],
};
