/// Партії перекладу KR16.2 і O17: записи, чий український текст уже описує правило 2024,
/// а не 2014. Список працює як храповик — кожна партія доливає імена, і жодне з них більше
/// не має права розійтися з XPHB.
///
/// Живе окремим модулем, бо його читають дві перевірки: звірка **полів**
/// (`differs-from-2014.test.ts`) і звірка **прози** (`spells-prose-2024.test.ts`).
/// Два списки розійшлися б із першою ж партією.
export const ALIGNED_WITH_XPHB: Record<string, string[]> = {
  "партія 1": [
    "Chill Touch",
    "Friends",
    "Message",
    "Mind Sliver",
    "Produce Flame",
    "Resistance",
    "Shillelagh",
    "Spare the Dying",
    "Thunderclap",
    "Vicious Mockery",
    "Word of Radiance",
    "Armor of Agathys",
    "Arms of Hadar",
    "Color Spray",
    "Command",
    "Detect Evil and Good",
    "Detect Magic",
    "Detect Poison and Disease",
    "False Life",
    "Goodberry",
    "Inflict Wounds",
    "Jump",
    "Witch Bolt",
    "Cordon of Arrows",
    "Enhance Ability",
    "Find Steed",
    "Gust of Wind",
    "Lesser Restoration",
    "Mind Spike",
    "Mirror Image",
  ],
  "партія 2": [
    "Pass without Trace",
    "Phantasmal Force",
    "Ray of Enfeeblement",
    "Aura of Vitality",
    "Blink",
    "Conjure Animals",
    "Conjure Barrage",
    "Crusader's Mantle",
    "Hunger of Hadar",
    "Leomund's Tiny Hut",
    "Speak with Plants",
    "Spirit Guardians",
    "Wind Wall",
    "Aura of Life",
    "Aura of Purity",
    "Banishment",
    "Confusion",
    "Conjure Minor Elementals",
    "Conjure Woodland Beings",
    "Grasping Vine",
    "Ice Storm",
    "Leomund's Secret Chest",
    "Antilife Shell",
    "Bigby's Hand",
    "Circle of Power",
    "Commune with Nature",
    "Conjure Elemental",
    "Contagion",
    "Destructive Wave",
    "Dream",
  ],
  "партія 3": [
    "Flame Strike",
    "Swift Quiver",
    "Yolande's Regal Presence",
    "Circle of Death",
    "Conjure Fey",
    "Globe of Invulnerability",
    "Guards and Wards",
    "Heroes' Feast",
    "Transport Via Plants",
    "Conjure Celestial",
    "Mordenkainen's Sword",
    "Prismatic Spray",
    "Teleport",
    "Antimagic Field",
    "Control Weather",
    "Holy Aura",
    "Tsunami",
    "Astral Projection",
    "Power Word Heal",
    "Power Word Kill",
    "Prismatic Wall",
    "Storm of Vengeance",
    "Weird",
  ],
  "партія 4": [
    "Divine Favor",
    "Sending",
    "Forcecage",
    "Poison Spray",
    "Healing Word",
    "Spiritual Weapon",
    "Cure Wounds",
    "Magic Weapon",
    "Mass Healing Word",
    "Blindness/Deafness",
    "Mass Cure Wounds",
    "Enthrall",
    "Hail of Thorns",
    "Animal Shapes",
    "Thunderous Smite",
    "Earthquake",
    "Lightning Arrow",
    "Searing Smite",
    "Barkskin",
    "Reincarnate",
    "Blinding Smite",
    "Giant Insect",
    "Sleep",
    "Blade Ward",
    "True Strike",
    "Wrathful Smite",
    "Staggering Smite",
    "Hex",
    "Flame Blade",
    "Toll the Dead",
    "Dragon's Breath",
    "Melf's Acid Arrow",
  ],
  "KR17.2 партія 1": [
    "Guidance",
    "Darkvision",
    "Shapechange",
    "Detect Thoughts",
    "Mass Suggestion",
    "Cloud of Daggers",
    "Counterspell",
    "Speak with Animals",
    "Suggestion",
    "Mind Blank",
    "Tasha's Hideous Laughter",
    "Otto's Irresistible Dance",
    "Rope Trick",
    "Dominate Monster",
    "Simulacrum",
    "Calm Emotions",
    "Arcane Gate",
    "Stinking Cloud",
    "Evard's Black Tentacles",
    "Dominate Beast",
    "Dominate Person",
    "Arcane Lock",
    "Beast Sense",
    "Moonbeam",
    "Antipathy/Sympathy",
  ],
  "KR17.2 партія 2": [
    "Greater Invisibility",
    "Invisibility",
    "Ensnaring Strike",
    "Mordenkainen's Faithful Hound",
    "Daylight",
    "Darkness",
    "Purify Food and Drink",
    "Create Food and Water",
    "Chromatic Orb",
    "Polymorph",
    "Enlarge/Reduce",
    "Imprisonment",
    "Compulsion",
    "Legend Lore",
    "Cloudkill",
    "Protection From Poison",
    "Animal Friendship",
    "Clone",
    "Power Word Stun",
    "Expeditious Retreat",
    "Greater Restoration",
    "Augury",
    "Alter Self",
    "Animal Messenger",
    "Geas",
  ],
  "KR17.2 партія 3": [
    "Charm Person",
    "Nystul's Magic Aura",
    "Awaken",
    "Phantasmal Killer",
    "Divine Word",
    "Conjure Volley",
    "Reverse Gravity",
    "Continual Flame",
    "Shocking Grasp",
    "Hunter's Mark",
    "Crown of Madness",
    "Entangle",
    "See Invisibility",
    "Tongues",
    "Blade Barrier",
    "Dissonant Whispers",
    "Demiplane",
    "Sequester",
    "Dimension Door",
    "Thorn Whip",
    "True Seeing",
    "Creation",
    "Incendiary Cloud",
    "Scrying",
    "Delayed Blast Fireball",
  ],
  "KR17.2 партія 4": [
    "Sleet Storm",
    "Find the Path",
    "Fire Storm",
    "Water Walk",
    "Seeming",
    "Wind Walk",
    "Eldritch Blast",
    "Dispel Evil and Good",
    "Hold Monster",
    "Sanctuary",
    "Divination",
    "Charm Monster",
    "Find Traps",
    "Flesh to Stone",
    "Harm",
    "Fog Cloud",
    "Thunderwave",
    "Ray of Sickness",
    "Drawmij's Instant Summons",
    "Disintegrate",
    "Burning Hands",
    "Compelled Duel",
    "Guiding Bolt",
    "Hold Person",
    "Scorching Ray",
  ],
  "KR17.2 партія 5": [
    "Plant Growth",
    "Gaseous Form",
    "Bane",
    "Lightning Bolt",
    "Feign Death",
    "Blight",
    "Flaming Sphere",
    "Regenerate",
    "Symbol",
    "Resurrection",
    "Faerie Fire",
    "Telekinesis",
    "Arcane Eye",
    "Fly",
    "Call Lightning",
    "Hellish Rebuke",
    "Bless",
    "Sacred Flame",
    "True Polymorph",
    "Mislead",
    "Meteor Swarm",
    "Identify",
    "Foresight",
    "Insect Plague",
    "Finger of Death",
  ],
  "KR17.2 партія 6": [
    "Sunbeam",
    "Freedom of Movement",
    "Hypnotic Pattern",
    "Fireball",
    "Illusory Script",
    "Fire Bolt",
    "Guardian of Faith",
    "Dispel Magic",
    "Cone of Cold",
    "Mordenkainen's Magnificent Mansion",
    "Prestidigitation",
    "Fear",
    "Web",
    "Feather Fall",
    "Light",
    "Shatter",
    "Sunburst",
    "Alarm",
    "Eyebite",
    "Synaptic Static",
    "Find Familiar",
    "Otiluke's Freezing Sphere",
    "Chain Lightning",
    "Protection From Evil and Good",
    "Longstrider",
  ],
  "KR17.2 партія 7": [
    "Summon Aberration",
    "Mage Armor",
    "Create or Destroy Water",
    "Vampiric Touch",
    "Raise Dead",
    "Mage Hand",
    "Wish",
    "Create Undead",
    "Glyph of Warding",
    "Modify Memory",
    "Planar Binding",
    "Blur",
    "Revivify",
    "Summon Construct",
    "Heroism",
    "Thaumaturgy",
    "Ray of Frost",
    "Elemental Weapon",
    "Hallucinatory Terrain",
    "Wall of Thorns",
    "Spider Climb",
    "Aid",
    "Locate Animals or Plants",
    "Druidcraft",
    "Summon Celestial",
  ],
  "KR17.2 партія 8": [
    "Vitriolic Sphere",
    "Fabricate",
    "Zone of Truth",
    "Comprehend Languages",
    "Summon Fiend",
    "Control Water",
    "Summon Fey",
    "Meld Into Stone",
    "Summon Elemental",
    "Summon Beast",
    "Wall of Ice",
    "Magic Missile",
    "Project Image",
    "Spike Growth",
    "Heat Metal",
    "Major Image",
    "Rary's Telepathic Bond",
    "Disguise Self",
    "Water Breathing",
    "Animate Dead",
    "Nondetection",
    "Phantom Steed",
    "Maze",
    "Stone Shape",
    "Wall of Fire",
  ],
  "KR17.2 партія 9": [
    "Speak with Dead",
    "Locate Creature",
    "Magic Jar",
    "Clairvoyance",
    "Mordenkainen's Private Sanctum",
    "Knock",
    "Ice Knife",
    "Magic Circle",
    "Silence",
    "Death Ward",
    "Minor Illusion",
    "Misty Step",
    "Shield",
    "Programmed Illusion",
    "Commune",
    "Shield of Faith",
    "Teleportation Circle",
    "Mending",
    "True Resurrection",
    "Warding Bond",
    "Silent Image",
    "Forbiddance",
    "Wall of Stone",
    "Wall of Force",
    "Locate Object",
  ],
  "KR17.2 партія 10": [
    "Contact Other Plane",
    "Slow",
    "Haste",
    "Gate",
    "Grease",
    "Fire Shield",
    "Passwall",
    "Word of Recall",
    "Plane Shift",
    "Tree Stride",
    "Summon Undead",
    "Levitate",
    "Magic Mouth",
    "Move Earth",
    "Steel Wind Strike",
    "Time Stop",
    "Unseen Servant",
    "Planar Ally",
    "Mirage Arcane",
    "Tenser's Floating Disk",
    "Gentle Repose",
    "Beacon of Hope",
    "Protection From Energy",
    "Remove Curse",
  ],
  "поза партіями": ["Bestow Curse", "Animate Objects"],
};
