import { ItemRarity, MagicItemType, Prisma, PrismaClient } from "../../src/generated/prisma"

export const seedMagicItems = async (prisma: PrismaClient) => {
    console.log('🧪 Додаємо магічні предмети для Replicate Magic Item...')
    const items: Prisma.MagicItemCreateInput[] = [
        // 6th-level replicables
		{
			name: 'Boots of Elvenkind',
			itemType: MagicItemType.WONDROUS_ITEM,
			rarity: ItemRarity.UNCOMMON,
			description: 'Тихі кроки. Перевірки Спритності (Непомітність) здійснюються з перевагою.',
			requiresAttunement: false,
		},
        {
            name: 'Cloak of Elvenkind',
            itemType: MagicItemType.WONDROUS_ITEM,
            rarity: ItemRarity.UNCOMMON,
            description: 'Плащ ельфів. Складно помітити вас.',
            requiresAttunement: true,
        },
        {
            name: 'Cloak of the Manta Ray',
            itemType: MagicItemType.WONDROUS_ITEM,
            rarity: ItemRarity.UNCOMMON,
            description: 'Дає швидкість плавання і дихання під водою.',
            requiresAttunement: false,
        },
        {
            name: 'Eyes of Charming',
            itemType: MagicItemType.WONDROUS_ITEM,
            rarity: ItemRarity.UNCOMMON,
            description: '3 заряди: зачарування осіб.',
            requiresAttunement: true,
        },
        {
            name: 'Gloves of Thievery',
            itemType: MagicItemType.WONDROUS_ITEM,
            rarity: ItemRarity.UNCOMMON,
            description: '+5 до Ловкості рук і Злому замків.',
            requiresAttunement: false,
        },
        {
            name: 'Lantern of Revealing',
            itemType: MagicItemType.WONDROUS_ITEM,
            rarity: ItemRarity.UNCOMMON,
            description: 'Виявляє невидимих істот у світлі.',
            requiresAttunement: false,
        },
        {
            name: 'Pipes of Haunting',
            itemType: MagicItemType.WONDROUS_ITEM,
            rarity: ItemRarity.UNCOMMON,
            description: 'Лякання музикою.',
            requiresAttunement: false,
        },
        {
            name: 'Ring of Water Walking',
            itemType: MagicItemType.RING,
            rarity: ItemRarity.UNCOMMON,
            description: 'Ходіння по воді.',
            requiresAttunement: false,
        },

        // 10th-level replicables
        {
            name: 'Boots of Striding and Springing',
            itemType: MagicItemType.WONDROUS_ITEM,
            rarity: ItemRarity.UNCOMMON,
            description: 'Швидкий крок і стрибок.',
            requiresAttunement: true,
        },
        {
            name: 'Boots of the Winterlands',
            itemType: MagicItemType.WONDROUS_ITEM,
            rarity: ItemRarity.RARE,
            description: 'Холодостійкість, пересування по снігу/льоду.',
            requiresAttunement: true,
        },
        {
            name: 'Bracers of Archery',
            itemType: MagicItemType.WONDROUS_ITEM,
            rarity: ItemRarity.UNCOMMON,
            description: '+2 до шкоди з луками.',
            requiresAttunement: true,
        },
        {
            name: 'Brooch of Shielding',
            itemType: MagicItemType.WONDROUS_ITEM,
            rarity: ItemRarity.UNCOMMON,
            description: 'Опір до сили і імунітет до магічних снарядів.',
            requiresAttunement: true,
        },
        {
            name: 'Cloak of Protection',
            itemType: MagicItemType.WONDROUS_ITEM,
            rarity: ItemRarity.UNCOMMON,
            description: '+1 до КБ і ряткидків.',
            requiresAttunement: true,
        },
        {
            name: 'Eyes of the Eagle',
            itemType: MagicItemType.WONDROUS_ITEM,
            rarity: ItemRarity.UNCOMMON,
            description: 'Перевага на спостереження на дальній дистанції.',
            requiresAttunement: true,
        },
        {
            name: 'Gauntlets of Ogre Power',
            itemType: MagicItemType.WONDROUS_ITEM,
            rarity: ItemRarity.UNCOMMON,
            description: 'Сила стає 19.',
            requiresAttunement: true,
        },
        {
            name: 'Gloves of Missile Snaring',
            itemType: MagicItemType.WONDROUS_ITEM,
            rarity: ItemRarity.UNCOMMON,
            description: 'Схоплюйте снаряди.',
            requiresAttunement: true,
        },
        {
            name: 'Gloves of Swimming and Climbing',
            itemType: MagicItemType.WONDROUS_ITEM,
            rarity: ItemRarity.UNCOMMON,
            description: '+5 до Атлетики для плавання/лазіння, без перевірок у певних умовах.',
            requiresAttunement: true,
        },
        {
            name: 'Hat of Disguise',
            itemType: MagicItemType.WONDROUS_ITEM,
            rarity: ItemRarity.UNCOMMON,
            description: 'Викликає Маскування [Disguise Self].',
            requiresAttunement: true,
        },
        {
            name: 'Headband of Intellect',
            itemType: MagicItemType.WONDROUS_ITEM,
            rarity: ItemRarity.UNCOMMON,
            description: 'Інтелект стає 19.',
            requiresAttunement: true,
        },
        {
            name: 'Helm of Telepathy',
            itemType: MagicItemType.WONDROUS_ITEM,
            rarity: ItemRarity.RARE,
            description: 'Телепатія, читання думок.',
            requiresAttunement: true,
        },
        {
            name: 'Medallion of Thoughts',
            itemType: MagicItemType.WONDROUS_ITEM,
            rarity: ItemRarity.UNCOMMON,
            description: 'Читання думок (заряди).',
            requiresAttunement: true,
        },
        {
            name: 'Necklace of Adaptation',
            itemType: MagicItemType.WONDROUS_ITEM,
            rarity: ItemRarity.UNCOMMON,
            description: 'Дихання в будь-якому середовищі; захист від газів.',
            requiresAttunement: true,
        },
        {
            name: 'Periapt of Wound Closure',
            itemType: MagicItemType.WONDROUS_ITEM,
            rarity: ItemRarity.UNCOMMON,
            description: 'Подвоює відновлення ХП, стабілізує автоматично.',
            requiresAttunement: true,
        },
        {
            name: 'Pipes of the Sewers',
            itemType: MagicItemType.WONDROUS_ITEM,
            rarity: ItemRarity.UNCOMMON,
            description: 'Контроль над щурами.',
            requiresAttunement: true,
        },
        {
            name: 'Quiver of Ehlonna',
            itemType: MagicItemType.WONDROUS_ITEM,
            rarity: ItemRarity.UNCOMMON,
            description: 'Магічний колчан для зберігання.',
            requiresAttunement: false,
        },
        {
            name: 'Ring of Jumping',
            itemType: MagicItemType.RING,
            rarity: ItemRarity.UNCOMMON,
            description: 'Заклинання Стрибок [Jump] при активації.',
            requiresAttunement: true,
        },
        {
            name: 'Ring of Mind Shielding',
            itemType: MagicItemType.RING,
            rarity: ItemRarity.UNCOMMON,
            description: 'Захист від читання думок/виявлення.',
            requiresAttunement: true,
        },
        {
            name: 'Slippers of Spider Climbing',
            itemType: MagicItemType.WONDROUS_ITEM,
            rarity: ItemRarity.UNCOMMON,
            description: 'Ходіння по стінах/стелях.',
            requiresAttunement: true,
        },
        {
            name: 'Ventilating Lungs',
            itemType: MagicItemType.WONDROUS_ITEM,
            rarity: ItemRarity.RARE,
            description: 'Вентильовані легені (Eberron).',
            requiresAttunement: true,
        },
        {
            name: 'Winged Boots',
            itemType: MagicItemType.WONDROUS_ITEM,
            rarity: ItemRarity.UNCOMMON,
            description: 'Обмежений політ.',
            requiresAttunement: true,
        },

        // 14th-level replicables
        {
            name: 'Amulet of Health',
            itemType: MagicItemType.WONDROUS_ITEM,
            rarity: ItemRarity.RARE,
            description: 'Стат CON = 19.',
            requiresAttunement: true,
        },
        {
            name: 'Arcane Propulsion Arm',
            itemType: MagicItemType.WONDROUS_ITEM,
            rarity: ItemRarity.VERY_RARE,
            description: 'Протез-рука з пропульсією (Eberron).',
            requiresAttunement: true,
        },
        {
            name: 'Belt of Hill Giant Strength',
            itemType: MagicItemType.WONDROUS_ITEM,
            rarity: ItemRarity.RARE,
            description: 'Сила = 21.',
            requiresAttunement: true,
        },
        {
            name: 'Boots of Levitation',
            itemType: MagicItemType.WONDROUS_ITEM,
            rarity: ItemRarity.RARE,
            description: 'Левітація.',
            requiresAttunement: true,
        },
        {
            name: 'Boots of Speed',
            itemType: MagicItemType.WONDROUS_ITEM,
            rarity: ItemRarity.RARE,
            description: 'Подвоєна швидкість; реакції ворогів з перешкодою.',
            requiresAttunement: true,
        },
        {
            name: 'Bracers of Defense',
            itemType: MagicItemType.WONDROUS_ITEM,
            rarity: ItemRarity.RARE,
            description: '+2 до КБ без броні/щита.',
            requiresAttunement: true,
        },
        {
            name: 'Cloak of the Bat',
            itemType: MagicItemType.WONDROUS_ITEM,
            rarity: ItemRarity.RARE,
            description: 'Політ/перетворення у кажана в темряві.',
            requiresAttunement: true,
        },
        {
            name: 'Dimensional Shackles',
            itemType: MagicItemType.WONDROUS_ITEM,
            rarity: ItemRarity.RARE,
            description: 'Кайдани вимірів.',
            requiresAttunement: false,
        },
        {
            name: 'Gem of Seeing',
            itemType: MagicItemType.WONDROUS_ITEM,
            rarity: ItemRarity.RARE,
            description: 'Справжнє бачення на час зарядженості.',
            requiresAttunement: true,
        },
        {
            name: 'Horn of Blasting',
            itemType: MagicItemType.WONDROUS_ITEM,
            rarity: ItemRarity.RARE,
            description: 'Конус звукової шкоди, шанс зламатись.',
            requiresAttunement: false,
        },
        {
            name: 'Ring of Free Action',
            itemType: MagicItemType.RING,
            rarity: ItemRarity.RARE,
            description: 'Не сповільнюється рух/параліч.',
            requiresAttunement: true,
        },
        {
            name: 'Ring of Protection',
            itemType: MagicItemType.RING,
            rarity: ItemRarity.RARE,
            description: '+1 до КБ і ряткидків.',
            requiresAttunement: true,
        },
        {
            name: 'Ring of the Ram',
            itemType: MagicItemType.RING,
            rarity: ItemRarity.RARE,
            description: 'Силовий таран (заряди).',
            requiresAttunement: true,
        },
    ]

    for (const item of items) {
        await prisma.magicItem.upsert({
            where: { name: item.name },
            update: {},
            create: item,
        })
    }
    console.log(`✅ Додано/оновлено магічних предметів: ${items.length}`)
}
