import { InfusionTargetType, Prisma, PrismaClient } from "../../../src/generated/prisma";

export const seedInfusions = async ( prisma: PrismaClient ) => {
    console.log( "🧪 Додаємо Вливання (Infusions)..." );

    const infusions: Prisma.InfusionCreateInput[] = [
        {
            name: "Покращений арканний фокус",
            engName: "Enhanced Arcane Focus",
            minArtificerLevel: 2,
            targetType: InfusionTargetType.WAND_ROD_STAFF,
            requiresAttunement: true,
            spellAttackBonus: 1,
            increasesAtLevel10By: 1,
            feature: { connect: { engName: "Infusion: Enhanced Arcane Focus" } },
        },
        {
            name: "Покращений захист",
            engName: "Enhanced Defense",
            minArtificerLevel: 2,
            targetType: InfusionTargetType.ARMOR,
            requiresAttunement: false,
            bonusToAC: 1,
            increasesAtLevel10By: 1,
            feature: { connect: { engName: "Infusion: Enhanced Defense" } },
        },
        {
            name: "Покращена зброя",
            engName: "Enhanced Weapon",
            minArtificerLevel: 2,
            targetType: InfusionTargetType.WEAPON,
            requiresAttunement: false,
            bonusToAttackRoll: 1,
            bonusToDamage: 1,
            increasesAtLevel10By: 1,
            feature: { connect: { engName: "Infusion: Enhanced Weapon" } },
        },
        {
            name: "Повертальна зброя",
            engName: "Returning Weapon",
            minArtificerLevel: 2,
            targetType: InfusionTargetType.WEAPON,
            requiresAttunement: false,
            bonusToAttackRoll: 1,
            bonusToDamage: 1,
            feature: { connect: { engName: "Infusion: Returning Weapon" } },
        },
        {
            name: "Повторний постріл",
            engName: "Repeating Shot",
            minArtificerLevel: 2,
            targetType: InfusionTargetType.WEAPON,
            requiresAttunement: true,
            bonusToAttackRoll: 1,
            bonusToDamage: 1,
            feature: { connect: { engName: "Infusion: Repeating Shot" } },
        },
        {
            name: "Промениста зброя",
            engName: "Radiant Weapon",
            minArtificerLevel: 6,
            targetType: InfusionTargetType.WEAPON,
            requiresAttunement: true,
            bonusToAttackRoll: 1,
            bonusToDamage: 1,
            feature: { connect: { engName: "Infusion: Radiant Weapon" } },
        },
        {
            name: "Загострювач розуму",
            engName: "Mind Sharpener",
            minArtificerLevel: 2,
            targetType: InfusionTargetType.ARMOR,
            requiresAttunement: false,
            feature: { connect: { engName: "Infusion: Mind Sharpener" } },
        },
        {
            name: "Броня магічної сили",
            engName: "Armor of Magical Strength",
            minArtificerLevel: 2,
            targetType: InfusionTargetType.ARMOR,
            requiresAttunement: false,
            feature: { connect: { engName: "Infusion: Armor of Magical Strength" } },
        },
        {
            name: "Кільце підживлення заклять",
            engName: "Spell-Refueling Ring",
            minArtificerLevel: 6,
            targetType: InfusionTargetType.RING,
            requiresAttunement: true,
            restoresSpellSlotUpToLevel: 3,
            feature: { connect: { engName: "Infusion: Spell-Refueling Ring" } },
        },
        {
            name: "Відштовхувальний щит",
            engName: "Repulsion Shield",
            minArtificerLevel: 6,
            targetType: InfusionTargetType.SHIELD,
            requiresAttunement: true,
            bonusToAC: 1,
            feature: { connect: { engName: "Infusion: Repulsion Shield" } },
        },
        {
            name: "Стійка броня",
            engName: "Resistant Armor",
            minArtificerLevel: 6,
            targetType: InfusionTargetType.ARMOR,
            requiresAttunement: true,
            feature: { connect: { engName: "Infusion: Resistant Armor" } },
        },
        {
            name: "Чоботи звивистої стежки",
            engName: "Boots of the Winding Path",
            minArtificerLevel: 6,
            targetType: InfusionTargetType.BOOTS,
            requiresAttunement: true,
            feature: { connect: { engName: "Infusion: Boots of the Winding Path" } },
        },
        {
            name: "Шолом обізнаності",
            engName: "Helm of Awareness",
            minArtificerLevel: 10,
            targetType: InfusionTargetType.HELMET,
            requiresAttunement: true,
            feature: { connect: { engName: "Infusion: Helm of Awareness" } },
        },
        {
            name: "Арканний бронепривід",
            engName: "Arcane Propulsion Armor",
            minArtificerLevel: 14,
            targetType: InfusionTargetType.ARMOR,
            requiresAttunement: true,
            speedBonus: 5,
            feature: { connect: { engName: "Infusion: Arcane Propulsion Armor" } },
        },
        {
            name: "Слуга-гомункул",
            engName: "Homunculus Servant",
            minArtificerLevel: 2,
            targetType: InfusionTargetType.GEM_CRYSTAL,
            requiresAttunement: false,
            feature: { connect: { engName: "Infusion: Homunculus Servant" } },
        },
        // Replicate Magic Item (2nd-level)
        {
            name: "Репліка: Сумка зберігання",
            engName: "Replicate: Bag of Holding",
            minArtificerLevel: 2,
            targetType: InfusionTargetType.ANY,
            requiresAttunement: false,
            replicatedMagicItem: { connect: { engName: "Bag of Holding" } },
        },
        {
            name: "Репліка: Ковпак дихання водою",
            engName: "Replicate: Cap of Water Breathing",
            minArtificerLevel: 2,
            targetType: InfusionTargetType.ANY,
            requiresAttunement: false,
            replicatedMagicItem: { connect: { engName: "Cap of Water Breathing" } },
        },
        {
            name: "Репліка: Окуляри ночі",
            engName: "Replicate: Goggles of Night",
            minArtificerLevel: 2,
            targetType: InfusionTargetType.ANY,
            requiresAttunement: false,
            replicatedMagicItem: { connect: { engName: "Goggles of Night" } },
        },
        {
            name: "Репліка: Протез кінцівки",
            engName: "Replicate: Prosthetic Limb",
            minArtificerLevel: 2,
            targetType: InfusionTargetType.ANY,
            requiresAttunement: true,
            replicatedMagicItem: { connect: { engName: "Prosthetic Limb" } },
        },
        {
            name: "Репліка: Мотузка лазіння",
            engName: "Replicate: Rope of Climbing",
            minArtificerLevel: 2,
            targetType: InfusionTargetType.ANY,
            requiresAttunement: false,
            replicatedMagicItem: { connect: { engName: "Rope of Climbing" } },
        },
        {
            name: "Репліка: Камені послання",
            engName: "Replicate: Sending Stones",
            minArtificerLevel: 2,
            targetType: InfusionTargetType.ANY,
            requiresAttunement: false,
            replicatedMagicItem: { connect: { engName: "Sending Stones" } },
        },
        {
            name: "Репліка: Жезл виявлення магії",
            engName: "Replicate: Wand of Magic Detection",
            minArtificerLevel: 2,
            targetType: InfusionTargetType.ANY,
            requiresAttunement: false,
            replicatedMagicItem: { connect: { engName: "Wand of Magic Detection" } },
        },
        {
            name: "Репліка: Жезл таємниць",
            engName: "Replicate: Wand of Secrets",
            minArtificerLevel: 2,
            targetType: InfusionTargetType.ANY,
            requiresAttunement: false,
            replicatedMagicItem: { connect: { engName: "Wand of Secrets" } },
        },
        // Replicate Magic Item (6th-level)
        {
            name: "Репліка: Чоботи ельфів",
            engName: "Replicate: Boots of Elvenkind",
            minArtificerLevel: 6,
            targetType: InfusionTargetType.ANY,
            requiresAttunement: false,
            replicatedMagicItem: { connect: { engName: "Boots of Elvenkind" } },
        },
        {
            name: "Репліка: Плащ ельфів",
            engName: "Replicate: Cloak of Elvenkind",
            minArtificerLevel: 6,
            targetType: InfusionTargetType.ANY,
            requiresAttunement: true,
            replicatedMagicItem: { connect: { engName: "Cloak of Elvenkind" } },
        },
        {
            name: "Репліка: Плащ манти",
            engName: "Replicate: Cloak of the Manta Ray",
            minArtificerLevel: 6,
            targetType: InfusionTargetType.ANY,
            requiresAttunement: false,
            replicatedMagicItem: { connect: { engName: "Cloak of the Manta Ray" } },
        },
        {
            name: "Репліка: Очі чарування",
            engName: "Replicate: Eyes of Charming",
            minArtificerLevel: 6,
            targetType: InfusionTargetType.ANY,
            requiresAttunement: true,
            replicatedMagicItem: { connect: { engName: "Eyes of Charming" } },
        },
        {
            name: "Репліка: Рукавички злодія",
            engName: "Replicate: Gloves of Thievery",
            minArtificerLevel: 6,
            targetType: InfusionTargetType.ANY,
            requiresAttunement: false,
            replicatedMagicItem: { connect: { engName: "Gloves of Thievery" } },
        },
        {
            name: "Репліка: Ліхтар викриття",
            engName: "Replicate: Lantern of Revealing",
            minArtificerLevel: 6,
            targetType: InfusionTargetType.ANY,
            requiresAttunement: false,
            replicatedMagicItem: { connect: { engName: "Lantern of Revealing" } },
        },
        {
            name: "Репліка: Свистки жаху",
            engName: "Replicate: Pipes of Haunting",
            minArtificerLevel: 6,
            targetType: InfusionTargetType.ANY,
            requiresAttunement: false,
            replicatedMagicItem: { connect: { engName: "Pipes of Haunting" } },
        },
        {
            name: "Репліка: Перстень ходіння по воді",
            engName: "Replicate: Ring of Water Walking",
            minArtificerLevel: 6,
            targetType: InfusionTargetType.ANY,
            requiresAttunement: false,
            replicatedMagicItem: { connect: { engName: "Ring of Water Walking" } },
        },
        // Replicate Magic Item (10th-level)
        {
            name: "Репліка: Чоботи кроку і стрибка",
            engName: "Replicate: Boots of Striding and Springing",
            minArtificerLevel: 10,
            targetType: InfusionTargetType.ANY,
            requiresAttunement: true,
            replicatedMagicItem: { connect: { engName: "Boots of Striding and Springing" } },
        },
        {
            name: "Репліка: Чоботи Зимокраю",
            engName: "Replicate: Boots of the Winterlands",
            minArtificerLevel: 10,
            targetType: InfusionTargetType.ANY,
            requiresAttunement: true,
            replicatedMagicItem: { connect: { engName: "Boots of the Winterlands" } },
        },
        {
            name: "Репліка: Налучники стрільця",
            engName: "Replicate: Bracers of Archery",
            minArtificerLevel: 10,
            targetType: InfusionTargetType.ANY,
            requiresAttunement: true,
            replicatedMagicItem: { connect: { engName: "Bracers of Archery" } },
        },
        {
            name: "Репліка: Брошка захисту",
            engName: "Replicate: Brooch of Shielding",
            minArtificerLevel: 10,
            targetType: InfusionTargetType.ANY,
            requiresAttunement: true,
            replicatedMagicItem: { connect: { engName: "Brooch of Shielding" } },
        },
        {
            name: "Репліка: Плащ захисту",
            engName: "Replicate: Cloak of Protection",
            minArtificerLevel: 10,
            targetType: InfusionTargetType.ANY,
            requiresAttunement: true,
            replicatedMagicItem: { connect: { engName: "Cloak of Protection" } },
        },
        {
            name: "Репліка: Очі орла",
            engName: "Replicate: Eyes of the Eagle",
            minArtificerLevel: 10,
            targetType: InfusionTargetType.ANY,
            requiresAttunement: true,
            replicatedMagicItem: { connect: { engName: "Eyes of the Eagle" } },
        },
        {
            name: "Репліка: Рукавиці сили огра",
            engName: "Replicate: Gauntlets of Ogre Power",
            minArtificerLevel: 10,
            targetType: InfusionTargetType.ANY,
            requiresAttunement: true,
            replicatedMagicItem: { connect: { engName: "Gauntlets of Ogre Power" } },
        },
        {
            name: "Репліка: Рукавиці перехоплення",
            engName: "Replicate: Gloves of Missile Snaring",
            minArtificerLevel: 10,
            targetType: InfusionTargetType.ANY,
            requiresAttunement: true,
            replicatedMagicItem: { connect: { engName: "Gloves of Missile Snaring" } },
        },
        {
            name: "Репліка: Рукавиці плавання й лазіння",
            engName: "Replicate: Gloves of Swimming and Climbing",
            minArtificerLevel: 10,
            targetType: InfusionTargetType.ANY,
            requiresAttunement: true,
            replicatedMagicItem: { connect: { engName: "Gloves of Swimming and Climbing" } },
        },
        {
            name: "Репліка: Капелюх маскування",
            engName: "Replicate: Hat of Disguise",
            minArtificerLevel: 10,
            targetType: InfusionTargetType.ANY,
            requiresAttunement: true,
            replicatedMagicItem: { connect: { engName: "Hat of Disguise" } },
        },
        {
            name: "Репліка: Обруч інтелекту",
            engName: "Replicate: Headband of Intellect",
            minArtificerLevel: 10,
            targetType: InfusionTargetType.ANY,
            requiresAttunement: true,
            replicatedMagicItem: { connect: { engName: "Headband of Intellect" } },
        },
        {
            name: "Репліка: Шолом телепатії",
            engName: "Replicate: Helm of Telepathy",
            minArtificerLevel: 10,
            targetType: InfusionTargetType.ANY,
            requiresAttunement: true,
            replicatedMagicItem: { connect: { engName: "Helm of Telepathy" } },
        },
        {
            name: "Репліка: Медальйон думок",
            engName: "Replicate: Medallion of Thoughts",
            minArtificerLevel: 10,
            targetType: InfusionTargetType.ANY,
            requiresAttunement: true,
            replicatedMagicItem: { connect: { engName: "Medallion of Thoughts" } },
        },
        {
            name: "Репліка: Оберіг пристосування",
            engName: "Replicate: Necklace of Adaptation",
            minArtificerLevel: 10,
            targetType: InfusionTargetType.ANY,
            requiresAttunement: true,
            replicatedMagicItem: { connect: { engName: "Necklace of Adaptation" } },
        },
        {
            name: "Репліка: Амулет загоєння",
            engName: "Replicate: Periapt of Wound Closure",
            minArtificerLevel: 10,
            targetType: InfusionTargetType.ANY,
            requiresAttunement: true,
            replicatedMagicItem: { connect: { engName: "Periapt of Wound Closure" } },
        },
        {
            name: "Репліка: Свистки каналізації",
            engName: "Replicate: Pipes of the Sewers",
            minArtificerLevel: 10,
            targetType: InfusionTargetType.ANY,
            requiresAttunement: true,
            replicatedMagicItem: { connect: { engName: "Pipes of the Sewers" } },
        },
        {
            name: "Репліка: Колчан Елонни",
            engName: "Replicate: Quiver of Ehlonna",
            minArtificerLevel: 10,
            targetType: InfusionTargetType.ANY,
            requiresAttunement: false,
            replicatedMagicItem: { connect: { engName: "Quiver of Ehlonna" } },
        },
        {
            name: "Репліка: Перстень стрибка",
            engName: "Replicate: Ring of Jumping",
            minArtificerLevel: 10,
            targetType: InfusionTargetType.ANY,
            requiresAttunement: true,
            replicatedMagicItem: { connect: { engName: "Ring of Jumping" } },
        },
        {
            name: "Репліка: Перстень захисту розуму",
            engName: "Replicate: Ring of Mind Shielding",
            minArtificerLevel: 10,
            targetType: InfusionTargetType.ANY,
            requiresAttunement: true,
            replicatedMagicItem: { connect: { engName: "Ring of Mind Shielding" } },
        },
        {
            name: "Репліка: Капці павучого лазіння",
            engName: "Replicate: Slippers of Spider Climbing",
            minArtificerLevel: 10,
            targetType: InfusionTargetType.ANY,
            requiresAttunement: true,
            replicatedMagicItem: { connect: { engName: "Slippers of Spider Climbing" } },
        },
        {
            name: "Репліка: Вентиляційні легені",
            engName: "Replicate: Ventilating Lungs",
            minArtificerLevel: 10,
            targetType: InfusionTargetType.ANY,
            requiresAttunement: true,
            replicatedMagicItem: { connect: { engName: "Ventilating Lungs" } },
        },
        {
            name: "Репліка: Крилаті чоботи",
            engName: "Replicate: Winged Boots",
            minArtificerLevel: 10,
            targetType: InfusionTargetType.ANY,
            requiresAttunement: true,
            replicatedMagicItem: { connect: { engName: "Winged Boots" } },
        },
        // Replicate Magic Item (14th-level)
        {
            name: "Репліка: Амулет здоровʼя",
            engName: "Replicate: Amulet of Health",
            minArtificerLevel: 14,
            targetType: InfusionTargetType.ANY,
            requiresAttunement: true,
            replicatedMagicItem: { connect: { engName: "Amulet of Health" } },
        },
        {
            name: "Репліка: Арканна пропульсійна рука",
            engName: "Replicate: Arcane Propulsion Arm",
            minArtificerLevel: 14,
            targetType: InfusionTargetType.ANY,
            requiresAttunement: true,
            replicatedMagicItem: { connect: { engName: "Arcane Propulsion Arm" } },
        },
        {
            name: "Репліка: Пояс сили пагорбового велетня",
            engName: "Replicate: Belt of Hill Giant Strength",
            minArtificerLevel: 14,
            targetType: InfusionTargetType.ANY,
            requiresAttunement: true,
            replicatedMagicItem: { connect: { engName: "Belt of Hill Giant Strength" } },
        },
        {
            name: "Репліка: Чоботи левітації",
            engName: "Replicate: Boots of Levitation",
            minArtificerLevel: 14,
            targetType: InfusionTargetType.ANY,
            requiresAttunement: true,
            replicatedMagicItem: { connect: { engName: "Boots of Levitation" } },
        },
        {
            name: "Репліка: Чоботи швидкості",
            engName: "Replicate: Boots of Speed",
            minArtificerLevel: 14,
            targetType: InfusionTargetType.ANY,
            requiresAttunement: true,
            replicatedMagicItem: { connect: { engName: "Boots of Speed" } },
        },
        {
            name: "Репліка: Наручі захисту",
            engName: "Replicate: Bracers of Defense",
            minArtificerLevel: 14,
            targetType: InfusionTargetType.ANY,
            requiresAttunement: true,
            replicatedMagicItem: { connect: { engName: "Bracers of Defense" } },
        },
        {
            name: "Репліка: Плащ кажана",
            engName: "Replicate: Cloak of the Bat",
            minArtificerLevel: 14,
            targetType: InfusionTargetType.ANY,
            requiresAttunement: true,
            replicatedMagicItem: { connect: { engName: "Cloak of the Bat" } },
        },
        {
            name: "Репліка: Вимірні кайдани",
            engName: "Replicate: Dimensional Shackles",
            minArtificerLevel: 14,
            targetType: InfusionTargetType.ANY,
            requiresAttunement: false,
            replicatedMagicItem: { connect: { engName: "Dimensional Shackles" } },
        },
        {
            name: "Репліка: Самоцвіт бачення",
            engName: "Replicate: Gem of Seeing",
            minArtificerLevel: 14,
            targetType: InfusionTargetType.ANY,
            requiresAttunement: true,
            replicatedMagicItem: { connect: { engName: "Gem of Seeing" } },
        },
        {
            name: "Репліка: Ріг вибуху",
            engName: "Replicate: Horn of Blasting",
            minArtificerLevel: 14,
            targetType: InfusionTargetType.ANY,
            requiresAttunement: false,
            replicatedMagicItem: { connect: { engName: "Horn of Blasting" } },
        },
        {
            name: "Репліка: Перстень вільної дії",
            engName: "Replicate: Ring of Free Action",
            minArtificerLevel: 14,
            targetType: InfusionTargetType.ANY,
            requiresAttunement: true,
            replicatedMagicItem: { connect: { engName: "Ring of Free Action" } },
        },
        {
            name: "Репліка: Перстень захисту",
            engName: "Replicate: Ring of Protection",
            minArtificerLevel: 14,
            targetType: InfusionTargetType.ANY,
            requiresAttunement: true,
            replicatedMagicItem: { connect: { engName: "Ring of Protection" } },
        },
        {
            name: "Репліка: Перстень барана",
            engName: "Replicate: Ring of the Ram",
            minArtificerLevel: 14,
            targetType: InfusionTargetType.ANY,
            requiresAttunement: true,
            replicatedMagicItem: { connect: { engName: "Ring of the Ram" } },
        },
    ];

    for ( const it of infusions ) {
        await prisma.infusion.upsert( {
            where: { engName: it.engName },
            update: {},
            create: it as any,
        } );
    }

    console.log( "✅ Додано/оновлено Вливання" );
};
