/**
 * Build src/lib/prisma-enums.ts — the database enums as plain `as const` objects (KR46.2).
 * `@prisma/client` in the browser resolves to `.prisma/client/index-browser.js`, which drags the
 * Prisma runtime (~95 KB) into every chunk that reads one enum value. Client code imports enums
 * from here instead. Reads the generated client, so run it after `prisma generate` (`db:pull` does).
 * Run: bun run generate:prisma-enums
 */

import { writeFileSync } from "fs";
import { join } from "path";

import { $Enums } from "@prisma/client";

const OUTPUT_PATH = join(process.cwd(), "src/lib/prisma-enums.ts");

const HEADER = `// Generated by scripts/generate-prisma-enums.ts from @prisma/client. Do not edit.
// Client components import enum values from here: the \`@prisma/client\` browser entry carries the Prisma runtime.
`;

function renderEnum(name: string, values: Record<string, string>): string {
  const members = Object.entries(values)
    .map(([key, value]) => `  ${key}: ${JSON.stringify(value)},`)
    .join("\n");
  return `export const ${name} = {\n${members}\n} as const;\nexport type ${name} = (typeof ${name})[keyof typeof ${name}];\n`;
}

const enums = Object.entries($Enums as Record<string, Record<string, string>>);
writeFileSync(OUTPUT_PATH, [HEADER, ...enums.map(([name, values]) => renderEnum(name, values))].join("\n"));
console.log(`prisma-enums.ts: ${enums.length} enums`);
